# Generated by Django 2.2.10 on 2021-09-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='your_answer',
            field=models.CharField(blank=True, max_length=256, verbose_name='Свой ответ'),
        ),
    ]
