# Generated by Django 2.2.10 on 2021-09-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210927_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Answer', verbose_name='Ответ'),
        ),
    ]
